GET http://localhost:8888/trending?page=1
Content-Type: application/json

###
GET http://localhost:8888/test
Content-Type: application/json

###

GET http://localhost:8888/movie/1011985
Content-Type: application/json

###

GET http://localhost:8888/movies?page=30
Content-Type: application/json

