GET http://localhost:8888/trending?page=8&time_window=day&size=40
Content-Type: application/json

###
GET http://localhost:8888/test
Content-Type: application/json

###

GET http://localhost:8888/shows?page=2x
Content-Type: application/json

###

GET http://localhost:8888/movies?page=30x
Content-Type: application/json

